-- ==========================================
-- 03. PRODUCT ANALYSIS
-- ==========================================


-- ==========================================
-- 1. Total Products
-- ==========================================

SELECT
    COUNT(DISTINCT product_id) AS total_products
FROM products;


-- ==========================================
-- 2. Products by Category
-- ==========================================
-- Shows how many products belong to each
-- product category.

SELECT
    COALESCE(
        product_category_name,
        'Unknown'
    ) AS product_category,

    COUNT(DISTINCT product_id) AS total_products

FROM products

GROUP BY
    product_category_name

ORDER BY
    total_products DESC;


-- ==========================================
-- 3. Top Categories by Revenue
-- ==========================================
-- Connects products to order_items to calculate
-- revenue generated by each category.

SELECT
    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS product_category,

    COUNT(DISTINCT oi.order_id) AS total_orders,

    COUNT(oi.order_item_id) AS items_sold,

    ROUND(
        SUM(oi.price),
        2
    ) AS total_revenue

FROM products p

JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_category_name

ORDER BY
    total_revenue DESC;


-- ==========================================
-- 4. Top 10 Products by Revenue
-- ==========================================

SELECT
    p.product_id,

    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS product_category,

    COUNT(oi.order_item_id) AS items_sold,

    ROUND(
        SUM(oi.price),
        2
    ) AS total_revenue

FROM products p

JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_id,
    p.product_category_name

ORDER BY
    total_revenue DESC

LIMIT 10;


-- ==========================================
-- 5. Top 10 Products by Units Sold
-- ==========================================

SELECT
    p.product_id,

    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS product_category,

    COUNT(oi.order_item_id) AS units_sold,

    ROUND(
        SUM(oi.price),
        2
    ) AS total_revenue

FROM products p

JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_id,
    p.product_category_name

ORDER BY
    units_sold DESC

LIMIT 10;


-- ==========================================
-- 6. Average Product Selling Price
-- ==========================================
-- Uses actual transaction prices from order_items.

SELECT
    ROUND(
        AVG(price),
        2
    ) AS average_product_selling_price

FROM order_items;


-- ==========================================
-- 7. Product Category Performance
-- ==========================================
-- Combines product count, units sold,
-- revenue and average selling price.

SELECT
    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS product_category,

    COUNT(DISTINCT p.product_id) AS total_products,

    COUNT(oi.order_item_id) AS units_sold,

    ROUND(
        SUM(oi.price),
        2
    ) AS total_revenue,

    ROUND(
        AVG(oi.price),
        2
    ) AS average_selling_price

FROM products p

LEFT JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_category_name

ORDER BY
    total_revenue DESC;